# Generated by Django 4.2.7 on 2025-04-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_cart_created_at_remove_cart_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='allergens',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
